source "http://gems.github.com"
source "http://rubygems.org"

gem "jeweler"
gem "rake"
gem "bundler"
gem "activesupport"
gem "hashie"
gem "oauth2"
gem "json"
gem "rest-client", :require => "rest_client"
gem "fakeweb"
gem "rspec"
gem "echoe"
gem "rcov"
gem "redgreen"
